### ISSUE TITLE
Automatic forwarding to current season

### ISSUE THREAD

**Issue by Tonypsilon** [Tonypsilon/bmm.frontend#31]
As a user, when I go to bmm-schach.de/ or bmm-schach.de/home, I want to be forwarded to the current season.

- [x] route / is forwarded to the home component
- [x]  /home (the home component) queries a backend resource to get the current season as IdAndLabel
- [x] Has a season component inside with the given season in it.

**Comment by MichalDemcak** [comment]
If its free,  i can try to work on that.

**Comment by Tonypsilon** [comment]
Sure, have fun :)

**Comment by Tonypsilon** [comment]
Note: The Controller on backend side is the CurrentSeasonController

**Comment by MichalDemcak** [comment]
I have problem with creating database localy on backend 
spring.datasource.url=jdbc:mariadb://localhost:3306
spring.datasource.username=root
spring.datasource.password=dcfcc951
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
thats my database properties
and corse properties 
de.tonypsilon.bmm.cors.frontend.urls=http://xyz.com,*localhost:4200
The error that is occuring Invocation of init method failed; nested exception is liquibase.exception.LockException: liquibase.exception.DatabaseException: (conn=32) No database selected [Failed SQL: (1046) CREATE TABLE DATABASECHANGELOGLOCK (ID INT NOT NULL, `LOCKED` BIT(1) NOT NULL, LOCKGRANTED datetime NULL, LOCKEDBY VARCHAR(255) NULL, CONSTRAINT PK_DATABASECHANGELOGLOCK PRIMARY KEY (ID))]

**Comment by Tonypsilon** [comment]
you spring.datasource.url should be something like jdbc:mariadb://localhost:3306/myCoolDatabase (database name in the end). Did you create a database? If yes, then you need to put the name there. If no, note that "just" installing MariaDB doesn't set up a database yet, it only sets up the database managing program. You can always check that the connection details are working by connecting to the database for example via DBeaver.

**Comment by MichalDemcak** [comment]
Ok ive got now running backend and front end but i cant do nothing here like i created users but i cannot login.

**Comment by Tonypsilon** [comment]
How did you create the users then? There are some tests that set up test data, try one of de.tonypsilon.bmm.backend.application.IntegrationTestDataSetup, they set up at least a user "admin" with password "secret".

**Comment by MichalDemcak** [comment]
Ok tehre is correcteed pull request if you want to to view it, and i have 1 additional question are you using some devops connected with this project ?

**Comment by Tonypsilon** [comment]
PR all good, as mentioned sry for long response time and thanks again for your contribution!
